name: "Cake Decorating | Stoyanka Kostadinova"
description: "Wedding & Birthday cakes | Designing & Decorating | Fondant & Buttery"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true
navigation:
- text: HOME
  url: /
- text: ABOUT
  url: /about/
- text: GALLERY
  url: /gallery/
- text: Contact
  url: /contact/
