name: "Cake Decorating | Stoyanka Kostadinova"
description: "Wedding & Birthday cakes | Designing & Decorating | Fondant & Buttery"

url: "http://localhost:4000"

paginate: 10
<<<<<<< HEAD
=======
>>>>>>> 42bdfd60ea46c93fce2bb92f10ef4f739ab88ced
markdown: rdiscount
permalink: date
pygments: true
navigation:
- text: HOME
  url: /index.html
- text: ABOUT
  url: /about.html
- text: GALLERY
  url: /gallery.html
- text: Contact
  url: /contact.html
